name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version-file: ".bun-version"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
